export const OFFSPRING_NUMBER_CALCULATION_TYPES = {
  RANDOM: 'RANDOM',
  FROM_ENERGY: 'FROM_ENERGY',
};

export const NEURON_TYPE_INPUT = 0;
export const NEURON_TYPE_INTERNAL = 1;
export const NEURON_TYPE_OUTPUT = 2;

export const MIN_INPUT_NEURON_ID = 1;
export const MIN_INTERNAL_NEURON_ID = 128;
export const MIN_OUTPUT_NEURON_ID = 64;

export const MAX_16_BIT_INTEGER = 65535;
export const MAX_16_BIT_SIGNED_INTEGER = 32767;
export const MIN_16_BIT_SIGNED_INTEGER = -32768;
